const ProvinceITA = [
  { provi: "Agrigento" },
  { provi: "Alessandria" },
  { provi: "Ancona" },
  { provi: "Aosta" },
  { provi: "Arezzo" },
  { provi: "Ascoli Piceno" },
  { provi: "Asti" },
  { provi: "Avellino" },
  { provi: "Bari" },
  { provi: "Barletta-Andria-Trani" },
  { provi: "Belluno" },
  { provi: "Benevento" },
  { provi: "Bergamo" },
  { provi: "Biella" },
  { provi: "Bologna" },
  { provi: "Bolzano" },
  { provi: "Brescia" },
  { provi: "Brindisi" },
  { provi: "Cagliari" },
  { provi: "Caltanissetta" },
  { provi: "Campobasso" },
  { provi: "Carbonia-Iglesias" },
  { provi: "Caserta" },
  { provi: "Catania" },
  { provi: "Catanzaro" },
  { provi: "Chieti" },
  { provi: "Como" },
  { provi: "Cosenza" },
  { provi: "Cremona" },
  { provi: "Crotone" },
  { provi: "Cuneo" },
  { provi: "Enna" },
  { provi: "Fermo" },
  { provi: "Ferrara" },
  { provi: "Firenze" },
  { provi: "Foggia" },
  { provi: "Forlì-Cesena" },
  { provi: "Frosinone" },
  { provi: "Genova" },
  { provi: "Gorizia" },
  { provi: "Grosseto" },
  { provi: "Imperia" },
  { provi: "Isernia" },
  { provi: "L'Aquila" },
  { provi: "La Spezia" },
  { provi: "Latina" },
  { provi: "Lecce" },
  { provi: "Lecco" },
  { provi: "Livorno" },
  { provi: "Lodi" },
  { provi: "Lucca" },
  { provi: "Macerata" },
  { provi: "Mantova" },
  { provi: "Massa-Carrara" },
  { provi: "Matera" },
  { provi: "Medio Campidano" },
  { provi: "Messina" },
  { provi: "Milano" },
  { provi: "Modena" },
  { provi: "Monza e della Brianza" },
  { provi: "Napoli" },
  { provi: "Novara" },
  { provi: "Nuoro" },
  { provi: "Ogliastra" },
  { provi: "Olbia-Tempio" },
  { provi: "Oristano" },
  { provi: "Padova" },
  { provi: "Palermo" },
  { provi: "Parma" },
  { provi: "Pavia" },
  { provi: "Perugia" },
  { provi: "Pesaro e Urbino" },
  { provi: "Pescara" },
  { provi: "Piacenza" },
  { provi: "Pisa" },
  { provi: "Pistoia" },
  { provi: "Pordenone" },
  { provi: "Potenza" },
  { provi: "Prato" },
  { provi: "Ragusa" },
  { provi: "Ravenna" },
  { provi: "Reggio Calabria" },
  { provi: "Reggio Emilia" },
  { provi: "Rieti" },
  { provi: "Rimini" },
  { provi: "Roma" },
  { provi: "Rovigo" },
  { provi: "Salerno" },
  { provi: "Sassari" },
  { provi: "Savona" },
  { provi: "Siena" },
  { provi: "Siracusa" },
  { provi: "Sondrio" },
  { provi: "Taranto" },
  { provi: "Teramo" },
  { provi: "Terni" },
  { provi: "Torino" },
  { provi: "Trapani" },
  { provi: "Trento" },
  { provi: "Treviso" },
  { provi: "Trieste" },
  { provi: "Udine" },
  { provi: "Varese" },
  { provi: "Venezia" },
  { provi: "Verbano-Cusio-Ossola" },
  { provi: "Vercelli" },
  { provi: "Verona" },
  { provi: "Vibo Valentia" },
  { provi: "Vicenza" },
  { provi: "Viterbo" }
];

export default ProvinceITA;